version: '2.1'

services:
  infinispan:
    image: infinispan/server:14.0.4.Final
    container_name: infinispan
    ports:
      - "11222:11222"
    command: "-c infinispan-demo.xml"
    volumes:
      - ./infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan-demo.xml:z
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11222/rest/v2/cache-managers/default/health/status" ]
      interval: 1s
      timeout: 30s
      retries: 50

  data-index:
    container_name: data-index
    image: quay.io/kiegroup/kogito-data-index-infinispan:${KOGITO_VERSION}
    ports:
      - "8180:8080"
    depends_on:
      infinispan:
        condition: service_healthy
    volumes:
      - ./persistence:/home/kogito/data/protobufs/
    environment:
      QUARKUS_INFINISPAN_CLIENT_HOSTS: infinispan:11222
      QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      KOGITO_DATA_INDEX_PROPS: -Dkogito.protobuf.folder=/home/kogito/data/protobufs/
      KOGITO_DATA_INDEX_QUARKUS_PROFILE: "http-events-support"
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"

  jobs-service:
    container_name: jobs-service
    image: quay.io/kiegroup/kogito-jobs-service-infinispan:${KOGITO_VERSION}
    ports:
      - "8580:8080"
    depends_on:
      infinispan:
        condition: service_healthy
    environment:
      QUARKUS_HTTP_PORT: 8580
      QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"
      QUARKUS_INFINISPAN_CLIENT_HOSTS: infinispan:11222
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      QUARKUS_PROFILE: "http-events-support"
      KOGITO_SERVICE_URL: http://jobs-service:8580
      KOGITO_JOBS_SERVICE_HTTP_JOB_STATUS_CHANGE_EVENTS: true
      MP_MESSAGING_OUTGOING_KOGITO_JOB_SERVICE_JOB_STATUS_EVENTS_HTTP_URL: http://data-index:8180/jobs
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
      - "data-index:host-gateway"

  kogito-example-service:
    container_name: kogito-example-service
    image: dev.local/${USER}/kogito-example-service:1.0-SNAPSHOT
    profiles: [ "example", "all" ]
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      infinispan:
        condition: service_healthy
    volumes:
      - ./svg/:/home/kogito/data/svg/
    environment:
      QUARKUS_INFINISPAN_CLIENT_HOSTS: infinispan:11222
      QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"
      KOGITO_DATAINDEX_HTTP_URL: http://data-index:8180
      KOGITO_JOBS_SERVICE_URL: http://jobs-service:8580
      KOGITO_SERVICE_URL: http://${DOCKER_GATEWAY_HOST}:8080
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      KOGITO_QUARKUS_JVM_PROPS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    extra_hosts:
      - "data-index:host-gateway"
      - "jobs-service:host-gateway"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    profiles: [ "consoles", "all" ]
    ports:
      - "8480:8080"
    volumes:
      - ./keycloak/kogito-realm.json:/tmp/kogito-realm.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/realms/kogito" ]
      interval: 1s
      timeout: 1s
      retries: 50
    environment:
      KEYCLOAK_IMPORT: /tmp/kogito-realm.json

  management-console:
    container_name: management-console
    image: quay.io/kiegroup/kogito-management-console:${KOGITO_VERSION}
    profiles: [ "consoles", "all" ]
    ports:
      - 8280:8080
    depends_on:
      data-index:
        condition: service_started
      keycloak:
        condition: service_healthy
    volumes:
      - ./svg/:/home/kogito/data/svg/
    environment:
      KOGITO_DATAINDEX_HTTP_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8180/graphql
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      KOGITO_MANAGEMENT_CONSOLE_PROPS: -Dkogito.consoles.keycloak.config.url=http://localhost:8480/auth -Dkogito.consoles.keycloak.config.health-check-url=http://localhost:8480/auth/realms/kogito/.well-known/openid-configuration -Dkogito.svg.folder.path=/home/kogito/data/svg

  task-console:
    container_name: task-console
    image: quay.io/kiegroup/kogito-task-console:${KOGITO_VERSION}
    profiles: [ "consoles", "all" ]
    ports:
      - 8380:8080
    depends_on:
      data-index:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      KOGITO_DATAINDEX_HTTP_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8180/graphql
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      KOGITO_TASK_CONSOLE_PROPS: -Dkogito.consoles.keycloak.config.url=http://localhost:8480/auth -Dkogito.consoles.keycloak.config.health-check-url=http://localhost:8480/auth/realms/kogito/.well-known/openid-configuration -Dquarkus.http.cors=true