# Packaging
#quarkus.package.type=fast-jar

#https://quarkus.io/guides/openapi-swaggerui
quarkus.http.cors=true
quarkus.smallrye-openapi.path=/docs/openapi.json
quarkus.swagger-ui.always-include=true
quarkus.kogito.data-index.graphql.ui.always-include=true
quarkus.http.test-port=0

# Kogito-service
kogito.service.url=http://localhost:8080

#Job-service
kogito.jobs-service.url=http://localhost:8080

# to be reachable from the container running job-service
kogito.dataindex.http.url=http://localhost:8180
kogito.dataindex.ws.url=ws://localhost:8180

# run create tables scripts
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.hibernate-orm.database.generation=update

kogito.persistence.type=jdbc
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kogito-user
quarkus.datasource.password=kogito-pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kogito
quarkus.kogito.devservices.enabled=false

%infinispan.kogito.persistence.type=infinispan
%infinispan.quarkus.infinispan-client.hosts=localhost:11222
%infinispan.quarkus.infinispan-client.use-auth=false
%infinispan.quarkus.kogito.devservices.enabled=false

quarkus.native.native-image-xmx=8g

%container.quarkus.container-image.build=true
%container.quarkus.container-image.push=false
%container.quarkus.container-image.group=${USER}
%container.quarkus.container-image.registry=dev.local
%container.quarkus.container-image.tag=1.0-SNAPSHOT
%container.quarkus.jib.jvm-entrypoint=/home/kogito/kogito-app-launch.sh
%container.quarkus.jib.base-jvm-image=quay.io/kiegroup/kogito-runtime-jvm:latest
%container.quarkus.jib.working-directory=/home/kogito/bin
%container.quarkus.container-image.name=kogito-example-service
%container.quarkus.kogito.devservices.enabled=false


%dev.quarkus.kogito.devservices.enabled=true

kogito.users.admin.groups=admin
kogito.users.jdoe.groups=admin
kogito.users.bxf.groups=admin
kogito.users.test.groups=admin
kogito.users.user.groups=user